id: ICE20844B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:07:27+00:00'
last_modified: '2022-06-08T03:02:58.561807+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20189
  title: རླུང་ནག་ཁྲོད་ཀྱི་བྱ་རྒོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7CC3:
      image_group_id: I1KG23218
      title: ''
      total_pages: 198
      order: 1
      base_file: 7CC3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
