id: P005432
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 11:50:12.275246
source_metadata:
  id: bdr:W20189
  title: རླུང་ནག་ཁྲོད་ཀྱི་བྱ་རྒོད།
  author: ''
  volumes:
    048b517cfa344c318cdc8f0db02c909d:
      image_group_id: I1KG23218
      title: ''
      volume_number: 1
      total_pages: 198
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
